typography_spectrum: 0.8774316413328052
color:
  brandStrength: 0.021432710578665137
  lightness: 0.50422093574889
  saturation: 0.9378982493653893
  rhythmicContrast: 0.41671855119057
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.10176246706396341
author:
  name: Louis Dugal
  email: louisdugal@locationprince.com
  url: www.locationprince.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7eb91438-b666-4de3-8ada-0ea2c330ce24.ai
name: Location Prince
title: Location Prince
description: Roulottes de chantier - Conteneur d'entreposage
