typography_spectrum: 0.8504946965258569
color:
  brandStrength: 0.43083024537190795
  lightness: 0.8581991179380566
  saturation: 0.1907347314991057
  rhythmicContrast: 0.9105720054358244
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.06205733399838209
author:
  name: Louis Dugal
  email: louisdugal@locationprince.com
  url: www.locationprince.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7eb91438-b666-4de3-8ada-0ea2c330ce24.ai
name: Location Prince
title: Location Prince
description: Roulottes de chantier - Conteneur d'entreposage
